/* Plugin Template generated by Pawn Studio */

#include <sourcemod>

new g_cloakOffset;
new Handle:cloakValue

public Plugin:myinfo = 
{
	name = "Cloak Syphon",
	author = "Muridias",
	description = "Gives spies extra cloak when frags a player",
	version = "1.0",
	url = "www.bhslaugherhouse.com/tf2/forums"
}

public OnPluginStart(){
	g_cloakOffset = FindSendPropInfo("CTFPlayer", "m_flCloakMeter");
	HookEvent("player_death", Event_PlayerDeath);
	cloakValue = CreateConVar("sm_cloaksyphon", "15", "How much cloak to add", FCVAR_PROTECTED);
}

setCloakValue(client){
	new Float:entValue = GetEntDataFloat(client, g_cloakOffset);
	new Float:cValue = GetConVarFloat(cloakValue);
	new Float:sum = entValue + cValue;
	SetEntDataFloat(client, g_cloakOffset, Float:sum);
}

public Action:Event_PlayerDeath(Handle:event, const String:name[], bool:dontBroadcast){
	new attacker = GetClientOfUserId(GetEventInt(event, "attacker"));
	setCloakValue(attacker);
}

