<?php 
/**
 * SourceWeb common page footer view
 * 
 * @version $Id: html_footer.phtml,v 1.3 2007-12-04 12:19:45 seva Exp $
 */

if (false) { // This is to avoid HTML validation errors in Zend Studio
    ?><html><body><?php
}

require_once 'Zend/Version.php';

?>
</div>
</div>
<div id="footer">
	<!-- div class="page_footer">
		Powered by Zend Framework <?= Zend_Version::VERSION ?>
	</div -->
<span class="copyright">&copy; 2017 Jigglys FunHouse, all rights reserved.<br>Team Fortress&reg; and the Team Fortress logo are trademarks and/or registered trademarks of Valve Corporation&reg;. <br\> StarCraft&reg; II and Blizzard Entertainment&reg; are all trademarks or registered trademarks of Blizzard Entertainment in the United States and/or other countries. <br\> This site is in no way associated with or endorsed by Blizzard Entertainment&reg; nor Valve Corporation&reg;.</span><br/><br/></div>
</div>
</div>
</body>
</html>
