<?php

/**
 * SourceWeb common page header view
 * 
 * @version $Id: html_header.phtml,v 1.4 2007-12-12 13:56:49 roy Exp $
 */

echo '<?xml version="1.0" encoding="UTF-8" ?>';
?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
            "http://www.w3.org/TR/html4/strict.dtd">

<!-- DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" -->
    
<html xmlns="http://www.w3.org/1999/xhtml">


<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    
    <style type="text/css">
        @import "http://ajax.googleapis.com/ajax/libs/dojo/1.7.1/dojo/resources/dojo.css"
    </style>
    
    <script type="text/javascript"
            src="http://ajax.googleapis.com/ajax/libs/dojo/1.7.1/dojo/dojo.js"
            djConfig="parseOnLoad: true">
    </script>
    
    <script type="text/javascript">
        dojo.require("dijit.Dialog");
        dojo.require("dijit.form.Button");
        dojo.require("dijit.form.TextBox");
        dojo.require("dijit.form.FilteringSelect");
        dojo.require("dojo.parser");    // scan page for widgets and instantiate them   
    </script>

<?php
    //require_once 'steamauth/steamauth.php';
    $ingame = (strpos($_SERVER['HTTP_USER_AGENT'], "Valve Source Client") !== false);
    $session = new Zend_Session_Namespace();

    $style = Zend_Controller_Front::getInstance()->getRequest()->getParam('style');
    if (isset($style))
        $session->style = $style;
    else
        $style = $session->style;

    if ($style == "1")
    {
        $dojo_theme = "http://ajax.googleapis.com/ajax/libs/dojo/1.7.1/dijit/themes/soria/soria.css";
        $dojo_class = "scsoria";
    }
    else
    {
        $dojo_theme = "http://ajax.googleapis.com/ajax/libs/dojo/1.7.1/dijit/themes/claro/claro.css";
        $dojo_class = "scnoir";
        $style = "2";
    }
?>
    <style type="text/css">
        @import "<?= $dojo_theme ?>";
    </style>

    <link rel="stylesheet" type="text/css" href="/sc/css/style<?= $style ?>.css" />

    <title><?= isset($this->page_title) ? $this->page_title : 'SC' ?></title>
</head>

<body class="<?= $dojo_class ?>">

<div id="everything">
<div id="header">
        <br><a href="http://www.jigglysfunhouse.net/index.php"><img src="/sc/images/Jigglylogo.png" border="0"></a>
</div>

<div id="middle">
        <div id="navigation" class="<?= $dojo_class ?>">
    <table><tr>
        <td><a href="/sc/index">Home</a></td>
        <td><a href="/sc/faction/list/has_races/1">List Factions</a></td>

<?php if ($ingame) : ?>
        <td><a href="/sc/race/find">Find/List Races</a></td>
<?php else : ?>
        <td><div class="<?= $dojo_class ?>" dojoType="dijit.form.DropDownButton">
            <span style="display:none">Find/List Races</span>
            <div style="display:none" dojoType="dijit.TooltipDialog" id="findRaceDlg" title="Find Race">
                    <form action="/sc/race/find" method="post" validate="true" id="findRaceFrm"><table>
                        <tr>
                        <td><label for=race>By Name:</label></td>
                        <td>
                            <input dojoType=dijit.form.TextBox type="text" name="race" id="race" value="" />
                        <td/>
                        </tr>
                        <tr>
                        <td><label for=faction>By Faction:</label></td>
                        <td>
                            <select dojoType=dijit.form.FilteringSelect name="faction" id="faction">
                            <option value=""></option>
                            <option value="Terran">Terran</option>
                            <option value="Protoss">Protoss</option>
                            <option value="Zerg">Zerg</option>
                            <option value="HumanAlliance">Human Alliance</option>
                            <option value="OrcishHorde">Orcish Horde</option>
                            <option value="NightElf">Night Elf</option>
                            <option value="UndeadScourge">Undead Scourge</option>
                            <option value="BurningLegion">Burning Legion</option>
                            <option value="Hellbourne">Hellbourne</option>
                            <option value="TheLegion">The Legion</option>
                            <option value="Sentinel">Sentinel</option>
                            <option value="Naga">Naga</option>
                            <option value="Titan">Titan</option>
                            <option value="XelNaga">Xel'naga</option>
                            <option value="Pony">The Ponies</option>
                            </select>
                        </td>
                        </tr>
                        <tr>
                            <td colspan="2" align="center">
                            <input dojoType=dijit.form.TextBox type="hidden" name="list_race" id="list_race" value="list_race" />
                            <button dojoType=dijit.form.Button type="submit" name="submit">Search</button>
                            </td>
                    </tr>
                </table></form>
            </div>
        </div></td>
<?php endif; ?>
    
<?php if ($ingame) : ?>
        <td><a href="/sc/item/find">Find/List Items</a></td>
<?php else : ?>
        <td><div class="<?= $dojo_class ?>" dojoType="dijit.form.DropDownButton">
            <span style="display:none">Find/List Items</span>
            <div style="display:none" dojoType="dijit.TooltipDialog" id="findItemDlg" title="Find Item">
                    <form action="/sc/item/find" method="post" validate="true" id="findItemFrm"><table>
                        <tr>
                        <td><label for=item>By Name:</label></td>
                        <td>
                            <input dojoType=dijit.form.TextBox type="text" name="item" id="item" value="" />
                        <td/>
                        </tr>
                        <tr>
                        <td><label for=category>By Category:</label></td>
                        <td>
                            <select dojoType=dijit.form.FilteringSelect name="category" id="category">
                            <option value=""></option>
                            <option value="Protective Items">Protective</option>
                            <option value="Enhancement Items">Enhancement</option>
                            <option value="Combative Items">Combative</option>
                            <option value="Defensive Items">Defensive</option>
                            <option value="Mole Related Items">Mole Related</option>
                            <option value="Weapons">Weapons</option>
                            </select>
                        </td>
                        </tr>
                        <tr>
                            <td colspan="2" align="center">
                            <input dojoType=dijit.form.TextBox type="hidden" name="list_item" id="list_item" value="list_item" />
                            <button dojoType=dijit.form.Button type="submit" name="submit">Search</button>
                            </td>
                    </tr>
                </table></form>
            </div>
        </div></td>
<?php endif; ?>

<?php if ($ingame) : ?>
        <td><a href="/sc/player/find">Find/List Players</a></td>
<?php else : ?>
        <td><div class="<?= $dojo_class ?>" dojoType="dijit.form.DropDownButton">
            <span style="display:none">Find/List Players</span>
            <div style="display:none" dojoType="dijit.TooltipDialog" id="findPlayerDlg" title="Find Player">
                    <form action="/sc/player/find" method="post" validate="true" id="findPlayerFrm"><table>
                        <tr>
                        <td><label for=name>By Name:</label></td>
                        <td>
                            <input dojoType=dijit.form.TextBox type="text" name="name" id="name"
                                value="<?= isset($this->name) ? $this->escape($this->name) : '' ?>" />
                        <td/>
                        </tr>
                        <tr>
                        <td><label for=steamid>By Steam Id:</label></td>
                        <td>
                            <input dojoType=dijit.form.TextBox type="text" name="steamid" id="steamid"
                                 value="<?= isset($this->steamid) ? $this->escape($this->steamid) : '' ?>" />
                        </td>
                        </tr>
                        <tr>
                            <td colspan="2" align="center">
                            <input dojoType=dijit.form.TextBox type="hidden" name="list_player" id="list_player" value="list_player" />
                            <button dojoType=dijit.form.Button type="submit" name="submit">Search</button>
                            </td>
                    </tr>
                </table></form>
            </div>
        </div></td>
<?php endif; ?>

<?php if (isset($this->session) && $this->session->logged_in) : ?>
        <td><a href="/sc/player/show/user/<?= $this->session->username?>">Show  <?= $this->session->username ?></a></td>
        <td><a href="/sc/user/logout">Logout</a></td>
<?php else : ?>
        <td><div class="<?= $dojo_class ?>" dojoType="dijit.form.DropDownButton">
            <span style="display:none">Login</span>
            <div style="display:none" dojoType="dijit.TooltipDialog" id="loginDlg" title="Enter Login information">
            <form action="/sc/user/login" method="get" id="loginFrm"><table>
                <!--tr>
                        <td><label for="user">User:</label></td>
                        <td><input dojoType=dijit.form.TextBox type="text" name="user" id="user"></td>
                </tr-->
                <!--tr>
                        <td><label for="pwd">Password:</label></td>
                        <td><input dojoType=dijit.form.TextBox type="password" name="password" id="pwd"></td>
                </tr-->
                <!--tr>
                        <td colspan="2" align="center">
                            <button dojoType=dijit.form.Button type="submit" name="submit">Login</button>
                        </td>
                </tr-->
                <tr>
                    <td colspan="2" align="center">
                        <!--a href='/sc/user/login'><img src='http://cdn.steamcommunity.com/public/images/signinthroughsteam/sits_02.png'></a-->
                        Not Available Yet!
                    </td>
                </tr>
            </table></form>
            </div>
        </div></td>
<?php endif; ?>

    </tr></table>
    </div>
    
    <div id="middle_column">
