<?php

/**
 * Log in page
 * 
 * @version $Id: login.phtml,v 1.2 2007-12-04 12:19:45 seva Exp $
 */

// Render common HTML header
echo $this->render('partials/html_header.phtml');

?>

<script>
    dojo.addOnLoad(showDialog);
    function showDialog() {
        dijit.byId('signinDlg').show();
    }
</script>
    
<?php if (isset($this->error)): ?>
    <div class="error">
        <?= $this->escape($this->error); ?>
    </div>
<?php endif; ?>

<div style="display:none" class="tundra" dojoType="dijit.Dialog" id="signinDlg" title="Please Sign In">
    
    <form action="/sc/user/login" method="get" id="loginFrm">
        <a href='/sc/user/login'><img src='http://cdn.steamcommunity.com/public/images/signinthroughsteam/sits_02.png'></a>
    </form>
</div>

<?php if (isset($this->steamid)): ?>
    <div class="steamid">
        Steamid: <?= $this->escape($this->steamid); ?>
    </div>
<?php endif; ?>

<?= $this->render('partials/html_footer.phtml'); ?>
