<?php
/**
 * Player display page view
 * 
 * @version $Id: list.phtml,v 1.4 2007-12-04 16:54:49 seva Exp $
 */

require_once 'Zend/Controller/Front.php';

// Render common HTML header
echo $this->render('partials/html_header.phtml');

?>

	<h2>Faction List:</h2>
<?php if (isset($this->error)): ?>
	<div class="error">
		<?= $this->escape($this->error); ?>
	</div>
<?php elseif (count($this->paginator)): ?>
	<div class="faction_container" width="100%">
	<table class="faction_detail">
<?php foreach ($this->paginator as $item): ?>
		<tr>
			<td width="100%"><table width="100%">
				<tr>
					<table width="100%">
						<tr>
							<td><a href="<?= Zend_Controller_Front::getInstance()->getBaseUrl() . 
			'/sc/faction/show/id/' . urlencode($item['faction']) ?>"><img src="/sc/images/<?= $this->escape($item['image']) ?>" width="250" /></a></td>
							<td width="100%" style="vertical-align:top">
								<table class="race_title" width="100%">
									<tr>
										<th width='100%' style="text-align: center;"><a href="<?= Zend_Controller_Front::getInstance()->getBaseUrl() . 
			'/sc/faction/show/id/' . urlencode($item['faction']) ?>"><?= $this->escape($item['long_name']) ?></a></th>
									</tr>
								</table>
								<table width="100%">
									<tr>
										<td><?= $item['description'] ?></td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</tr>
			</td></table>
		</tr>
		<tr>
			<td width="100%"><img src="/sc/images/spacer.gif" width="100%" height="1"/></td>
		</tr>
<?php endforeach; ?>
	</table>
	</div>
	<?= $this->paginationControl($this->paginator, 'Sliding', 'pagination_control.phtml'); ?>
<?php else: ?>
	No factions have been selected.
<?php endif; ?>

<?= $this->render('partials/html_footer.phtml'); ?>
