<?php

/**
 * Find Player page
 * 
 * @version $Id: find.phtml,v 1.2 2007-12-04 12:19:45 seva Exp $
 */

// Render common HTML header
echo $this->render('partials/html_header.phtml');

?>

<?php if (isset($this->error)): ?>
	<div class="error">
		<?= $this->escape($this->error); ?>
	</div>
<?php endif; ?>

<div class="dialog_container" id="searchDlg" title="Find Player" style="margin:0 auto; text-align:center;">
	
	<form action="/sc/player/find" method="post">
		<div style="text-align:center;">Find Player</div><br>

		<label for="name">By Name:</label>
		<input type="text" name="name" id="name" value="" /><br />
		
		<label for="steamid">By Steam Id:</label>
		<input type="text" name="steamid" id="steamid"
			 value="<?= isset($this->steamid) ? $this->escape($this->steamid) : '' ?>" />
		<br />
		
		<div class="button_container">
			<input type="hidden" name="list_player" id="list_player" value="list_player" />
			<input type="submit" value="Search">
		</div>
	</form>
</div>

<div class="player_container">
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
</div>

<?= $this->render('partials/html_footer.phtml'); ?>
