<?php
/**
 * Player display page view
 * 
 * @version $Id: show.phtml,v 1.4 2007-12-04 16:54:49 seva Exp $
 */

require_once 'Zend/Controller/Front.php';

// Render common HTML header
echo $this->render('partials/html_header.phtml');

?>

<?php if (isset($this->error)): ?>
	<div class="error">
		<?= $this->escape($this->error); ?>
	</div>
<?php elseif (! empty($this->player)): ?>

<div class="player_container">
	<table class="player_detail">
		<tr>
			<th width="20%">Name :</th>
			<td width="25%"><?= $this->escape($this->player->name) ?></td>
			<td width="55%">&nbsp;</td>
		</tr>
		<tr>
			<th width="20%">Steam ID :</th>
			<td width="25%"><?= $this->escape($this->player->steamid) ?></td>
			<td width="55%">&nbsp;</td>
		</tr>
		<tr>
			<th width="20%">Overall Level :</th>
			<td width="25%"><?= $this->escape($this->player->overall_level) ?></td>
			<td width="55%">&nbsp;</td>
		</tr>
		<tr>
			<th width="20%">Crystals :</th>
			<td width="25%"><?= $this->escape($this->player->crystals) ?></td>
			<td width="55%">&nbsp;</td>
		</tr>
		<tr>
			<th width="20%">Vespene :</th>
			<td width="25%"><?= $this->escape($this->player->vespene) ?></td>
			<td width="55%">&nbsp;</td>
		</tr>
		<tr>
			<th width="20%">Last Time on Server :</th>
			<td width="25%"><?= $this->escape($this->player->last_update_date) ?></td>
			<td width="55%">&nbsp;</td>
		</tr>
	</table>
<?php if (isset($this->alias) && !empty($this->alias) && count($this->alias) > 0): ?>
	<table class="alias_detail" width='100%'>
		<tr>
			<th width="10%">Date</th>
			<th width="25%">SteamID</th>
			<th width="65%" style="text-align: left;">Alias</th>
		</tr>
<?php foreach ($this->alias as $alias): ?>
		<tr width='100%'>
			<td width="10%"><?= $this->escape($alias['last_used_date']) ?></td>
			<td width="25%"><?= $this->escape($alias['steamid']) ?></td>
			<td width="65%" style="text-align: left;"><?= $this->escape($alias['name']) ?></td>
		</tr>
<?php endforeach; ?>
	</table>
<?php endif; ?>

<?php if (isset($this->tech) && !empty($this->tech)): ?>
	<table class="tech_detail" width="100%">
		<tr>
			<th width="50px"></th>
			<th width="10%">Faction</th>
			<th width="10%">Race Count</th>
			<th width="10%">Tech Level</th>
			<th width="70%">&nbsp;</th>
		</tr>
<?php foreach ($this->tech as $tech): ?>
		<tr>
			<?php if (empty($tech['image'])): ?>
						<td width="50px"></td>
			<?php else: ?>
						<td width="50px"><img src="/sc/images/<?= $this->escape($tech['image']) ?>" width="38px" /></td>
			<?php endif; ?>
			<td width="25%"><?= $this->escape($tech['long_name']) ?></td>
			<td width="10%" style="text-align: center;"><?= $this->escape($tech['tech_count']) ?></td>
			<td width="10%" style="text-align: center;"><?= $this->escape($tech['tech_level']) ?></td>
			<td width="55%">&nbsp;</td>
		</tr>
<?php endforeach; ?>
	</table>
	<br/>
<?php endif; ?>

<?php if (isset($this->races) && !empty($this->races)): ?>
<?php foreach ($this->races as $race): ?>
	<div class="race_container" width="100%">
	<table class="race_detail" width="100%">
		<tr>
			<td width="100%"><img src="/sc/images/spacer.gif" width="100%" height="1"/></td>
		</tr>
		<tr>
			<td width="100%"><table width="100%">
				<tr>
					<table width="100%">
						<tr>
							<td><a href="<?= Zend_Controller_Front::getInstance()->getBaseUrl() . 
			'/sc/race/show/ident/' . urlencode($race['race_ident']) ?>"><img src="/sc/images/<?= $this->escape($race['image']) ?>" width="250" /></a></td>
							<td width="100%" style="vertical-align:top">
								<table class="race_title" width="100%">
									<tr>
										<th width='100%' style="text-align: center;"><a href="<?= Zend_Controller_Front::getInstance()->getBaseUrl() . 
			'/sc/race/show/ident/' . urlencode($race['race_ident']) ?>"><?= $this->escape($race['long_name']) ?></a></th>
									</tr>
								</table>
								<table class="race_data">
									<tr>
										<th width="75px">Faction :</th>
										<td><a href="<?= Zend_Controller_Front::getInstance()->getBaseUrl() . 
			'/sc/faction/show/id/' . urlencode($race['faction']) ?>"><?= $this->escape($race['faction_name']) ?></a></td>
									</tr>
									<tr>
										<th width="75px">Type :</th>
										<td><?= $this->escape($race['type']) ?></td>
									</tr>
<?php if (isset($race['parent_name']) && !empty($race['parent_name'])): ?>
									<tr>
										<th width="150px" align="right">Summoned From :</th>
										<td><a href="<?= Zend_Controller_Front::getInstance()->getBaseUrl() . 
			'/sc/race/show/name/' . urlencode($race['parent_name']) ?>"><?= $this->escape($race['parent_long_name']) ?></a></td>
									</tr>
<?php endif; ?>
<?php if (isset($race['required_level']) && $race['required_level'] > 0): ?>
									<tr>
										<th width="150px" align="right">Required Level :</th>
										<td><?= $this->escape($race['required_level']) ?></td>
									</tr>
<?php endif; ?>
<?php if (isset($race['tech_level']) && $race['tech_level'] > 0): ?>
									<tr>
										<th width="150px" align="right">Required Tech Level :</th>
										<td><?= $this->escape($race['tech_level']) ?></td>
									</tr>
<?php endif; ?>
									<tr>
										<th width="75px">XP :</th>
										<td><?= $this->escape($race['xp']) ?></td>
									</tr>
									<tr>
										<th width="75px">Level :</th>
										<td><?= $this->escape($race['level']) ?></td>
									</tr>
								</table>
								<table width="100%">
									<tr>
										<td><?= $race['description'] ?></td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</tr>
			</td></table>
		</tr>
	</table>
	<ul><table class="upgrade_detail" width='100%'>
		<tr>
			<th></th>
			<th></th>
			<th></th>
			<th colspan="3"><center>-Upgrade Requirement-</center></th>
			<th colspan="3"><center>----- Cost to Invoke -----</center></th>
			<th>Energy/</th>
			<th></th>
		</tr>
		<tr>
			<th></th>
			<th>Upgrade</th>
			<th><center>Levels</center></th>
			<th><center>Min Lvl</center></th>
			<th><center>Crystals</center></th>
			<th><center>Vespene</center></th>
			<th><center>Energy</center></th>
			<th><center>Crystals</center></th>
			<th><center>Vespene</center></th>
			<th><center>Second</center></th>
			<th>Description</th>
		</tr>
<?php foreach ($this->upgrades as $upgrade): ?>
<?php if ($upgrade['race_ident'] == $race['race_ident']): ?>
		<tr class='player_upgrades' width='100%'>
<?php if (empty($upgrade['image'])): ?>
			<td></td>
<?php else: ?>
			<td><img src="/sc/images/<?= $this->escape($upgrade['image']) ?>" width="38px" /></td>
<?php endif; ?>
			<td><b><?= $this->escape($upgrade['long_name']) ?><?= (($upgrade['category'] > 0) ? "<br><font color='cyan'> +ultimate" . $upgrade['category'] . "</font>" : "") ?></b></td>
			<td><center><?= intval($upgrade['upgrade_level'])."/".$upgrade['max_level'] ?></center></td>
			<td><center><?= ($upgrade['required_level'] > 1) ? $upgrade['required_level'] : "" ?></center></td>
			<td><center><?= ($upgrade['cost_crystals'] > 0) ? $upgrade['cost_crystals'] : "" ?></center></td>
			<td><center><?= ($upgrade['cost_vespene'] > 0) ? $upgrade['cost_vespene'] : "" ?></center></td>
			<td><center><?= ($upgrade['energy'] > 0) ? $upgrade['energy'] : "" ?></center></td>
			<td><center><?= ($upgrade['crystals'] > 0) ? $upgrade['crystals'] : "" ?></center></td>
			<td><center><?= ($upgrade['vespene'] > 0) ? $upgrade['vespene'] : "" ?></center></td>
			<td><center><?= ($upgrade['recurring_energy'] > 0) ? $upgrade['recurring_energy'] : "" ?></center></td>
			<td><?= $upgrade['description'].'&nbsp'.$upgrade['invoke'].'&nbsp'.$upgrade['bind'] ?></td>
		</tr>

<?php endif; ?>
<?php endforeach; ?>
		<tr>
			<td><img src="/images/spacer.gif" width="40px" height="1"/></td>
			<td><img src="/images/spacer.gif" width="100px" height="1"/></td>
			<td><img src="/images/spacer.gif" width="40px" height="1"/></td>
			<td><img src="/images/spacer.gif" width="40px" height="1"/></td>
			<td><img src="/images/spacer.gif" width="40px" height="1"/></td>
			<td><img src="/images/spacer.gif" width="40px" height="1"/></td>
			<td><img src="/images/spacer.gif" width="40px" height="1"/></td>
			<td><img src="/images/spacer.gif" width="40px" height="1"/></td>
			<td><img src="/images/spacer.gif" width="40px" height="1"/></td>
			<td><img src="/images/spacer.gif" width="40px" height="1"/></td>
			<td width="100%"></td>
		</tr>
	</table></ul>
	</div>
<?php endforeach; ?>
<?php endif; ?>
<?php else: ?>
	No player has been selected.
<?php endif; ?>
</div>

<?= $this->render('partials/html_footer.phtml'); ?>
