/*
File: immunity.inc
Description: All the immunity types.
Author(s): Anthony Iacono  
*/

#define IMMUNITY_COUNT 4

/* Pulled directly from the interface:
enum War3Immunity
{
	Immunity_Ultimates = 0, // Immune from ultimates
	Immunity_HealthTake = 1, // Immune from health taking
	Immunity_Explosion = 2, // Immune from explosion based stuff
	Immunity_ShopItems = 3, // Immune from shop items
}; */