<?php

/**
 * Default home page view
 *  
 * @author
 * @version
 */

// Render common HTML header
echo $this->render('partials/html_header.phtml');

// Render the common page headers
//echo $this->render('partials/player_list.phtml'); 

$this->headTitle('SourceCraft');
$this->placeholder('title')->set('Welcome');
?>

<div class="body_container">

	<h2>Welcome to SourceCraft</h2>
	<p><strong>SourceCraft</strong> is a TF2 mod that adds Role Playing (RPG) and Real Time Strategy (RTS) elements into the game.</p>
	<p> There are many races, mostly based on the StarCraft and WarCraft games, each with it's own strengths and weaknesses.  Each race also has certain upgrades (abilities) that they can use. When players first join the game, they will be prompted to choose a race. They can also change race at any time, but they won't become the new race until they respawn.</p>
	<p>There are also several "summon" races that are not available directly, they have to be "summoned" from another race that has the ability to summon it. An example is Protoss Archon, which is summoned from Protoss Templar.  </p>
	<p>Races are grouped into Factions, such as Terran, Protoss, Zerg, Human Alliance, Undead Scourge, Night Elf, Orcish Hord, etc, based on the backstory of the race. The race menu is then categorized by those factions.</p>
	<p>Players gain experience from kills and obtaining objectives, such as capping a flag, which are then used to gain levels in the race they are currently playing. Each level allows the player to choose an upgrade for that race, some of which are passive and others are invoked using a key bound to invoke a +ultimate command. All experience and levels are earned for the player's current race and are not transferrable to other races.  </p>
	<p>Players will also earn crystals and/or vespene from kills and/or objectives that allow them to purchase items in the shopmenu to add to their arsenal of abilities. Most are passive, but there are some items, such as jetpack, nades and mines, that are invoked by using a key bound to a +item command. Most items are lost when a player dies unless they own the Ankh of Reincarnation.</p>
	<p>Additionally, players will gain energy as they play, usually 1/second. Most race's upgrades consume energy and will not be invoked without a sufficient energy supply. When a player dies, any energy they have will be added to a special category of "accumulated energy". Only a few upgrades can use "accumulated energy", ones that require a large amount of energy such as summon races, which typically require 100-300 energy or more.  </p>
	<p>Several race's upgrades also consume Vespene, such as Zerg Drone's Mutate, and won't function without a sufficient vespene supply.</p>
	<p>Sourcecraft options are accessed by typing 'menu' into chat. From there you can do just about anything. For a description of the different races and what their abilities do type "raceinfo" into chat or refer to the <a href="http://sc.clanservers.com">sc.clanservers.com</a> web site. You can access the shop menu through the mod menu or by typing 'buy into chat.  Upgrades can be reassigned any time through the mod menu or by typing "reset" into chat. The next time you spawn you will be asked to reassign your upgrade points.</p>
	<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<?= $this->render('partials/html_footer.phtml'); ?>
