<?php
/**
 * Race display page view
 * 
 * @version $Id: list.phtml,v 1.4 2007-12-04 16:54:49 seva Exp $
 */

require_once 'Zend/Controller/Front.php';

// Render common HTML header
echo $this->render('partials/html_header.phtml');

?>

	<h2>Race List:</h2>
<?php if (isset($this->error)): ?>
	<div class="error">
		<?= $this->escape($this->error); ?>
	</div>
<?php elseif ($this->paginator && count($this->paginator)): ?>
	<div class="race_container" width="100%">
	<table class="race_detail">
<?php foreach ($this->paginator as $item): ?>
		<tr>
			<td width="100%"><table width="100%">
				<tr>
					<table width="100%">
						<tr>
							<td><a href="<?= Zend_Controller_Front::getInstance()->getBaseUrl() . 
			'/sc/race/show/ident/' . urlencode($item['race_ident']) ?>"><img src="/sc/images/<?= $this->escape($item['image']) ?>" width="250" /></a></td>
							<td width="100%" style="vertical-align:top">
								<table class="race_title" width="100%">
									<tr>
										<th width='100%' style="text-align: center;"><a href="<?= Zend_Controller_Front::getInstance()->getBaseUrl() . 
			'/sc/race/show/ident/' . urlencode($item['race_ident']) ?>"><?= $this->escape($item['long_name']) ?></a></th>
									</tr>
								</table>
								<table class="race_data">
									<tr>
										<th width="150px" align="right">Faction :</th>
										<td><a href="<?= Zend_Controller_Front::getInstance()->getBaseUrl() . 
			'/sc/faction/show/id/' . urlencode($item['faction']) ?>"><?= $this->escape($item['faction_name']) ?></a></td>
									</tr>
									<tr>
										<th width="150px" align="right">Type :</th>
										<td><?= $this->escape($item['type']) ?></td>
									</tr>
<?php if (isset($item['parent_name']) && !empty($item['parent_name'])): ?>
									<tr>
										<th width="150px" align="right">Summoned From :</th>
										<td><a href="<?= Zend_Controller_Front::getInstance()->getBaseUrl() . 
			'/sc/race/show/name/' . urlencode($item['parent_name']) ?>"><?= $this->escape($item['parent_long_name']) ?></a></td>
									</tr>
<?php endif; ?>
<?php if (isset($item['required_level']) && $item['required_level'] > 0): ?>
									<tr>
										<th width="150px" align="right">Required Level :</th>
										<td><?= $this->escape($item['required_level']) ?></td>
									</tr>
<?php endif; ?>
<?php if (isset($item['tech_level']) && $item['tech_level'] > 0): ?>
									<tr>
										<th width="150px" align="right">Required Tech Level :</th>
										<td><?= $this->escape($item['tech_level']) ?></td>
									</tr>
<?php endif; ?>
								</table>
								<table width="100%">
									<tr>
										<td><?= $item['description'] ?></td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</tr>
			</td></table>
		</tr>
<?php if (! empty($this->upgrades)): ?>
	<ul><table class="upgrade_detail" width='100%'>
		<tr>
			<th width="200px">Upgrade</th>
			<th width="100%">Description</th>
		</tr>
<?php foreach ($this->upgrades as $upgrade): ?>
<?php if ($upgrade['race_ident'] == $race['race_ident']): ?>
		<tr class='race_upgrades' width='100%'>
			<td width="200px"><li><?= $this->escape($upgrade['long_name']) ?></td>
			<td width="100%"><?= $upgrade['description'].'&nbsp'.$upgrade['invoke'].'&nbsp'.$upgrade['bind'] ?></td>
		</tr>
<?php endif; ?>
<?php endforeach; ?>
<?php endif; ?>
<?php endforeach; ?>
		<tr>
			<td width="100%"><img src="/sc/images/spacer.gif" width="100%" height="1"/></td>
		</tr>
	</table>
	</div>
	<?= $this->paginationControl($this->paginator, 'Sliding', 'pagination_control.phtml'); ?>
<?php else: ?>
	No race has been selected.
<?php endif; ?>

<?= $this->render('partials/html_footer.phtml'); ?>
